language: python - "3.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install python3-pip python3-setuptools python3-wheel
    - sudo pip3 install pip --upgrade
    - sudo apt-get remove python3-pip
install:
    - pip3 install --user sphinx travis-sphinx recommonmark sphinx_rtd_theme
script:
    # travis-sphinx build --source=./
    travis-sphinx build --source=./source

after_success:
    # travis-sphinx deploy
    travis-sphinx deploy --cname www.xuezhisd.top
