language: python - "3.7"

before_install:
    - ls
    - pwd
install:
    - pip install --user sphinx travis-sphinx recommonmark sphinx_rtd_theme

script:
    # travis-sphinx build --source=./
    travis-sphinx build --source=./source

after_success:
    # travis-sphinx deploy
    travis-sphinx deploy --cname www.xuezhisd.top
