language: python - "3.7"

branches:
  only:
    - master

before_install:
    - sudo apt-get update
    - sudo apt-get install python3-pip python3-setuptools python3-wheel
    - sudo pip3 install pip --upgrade
    - sudo apt-get remove python3-pip
#     - sudo apt-get install texlive-full
install:
#     - pip3 install --user sphinx travis-sphinx recommonmark sphinx_rtd_theme
    - pip3 install --user sphinx travis-sphinx recommonmark sphinx_rtd_theme
    - sudo apt-get install texlive-full
script:
    # travis-sphinx build --source=./
    #travis-sphinx build --source=./source
    ls
    make latexpdf
    pwd
    ls
    travis-sphinx build --source=./source --nowarn

after_success:
    # travis-sphinx deploy
    # travis-sphinx deploy --cname www.xuezhisd.top
    #travis-sphinx deploy --cname blog.xuezhisd.top
    travis-sphinx deploy -b master -c "note.xuezhisd.top" -m "update blog automatically by travis."
